blank_issues_enabled: true
contact_links:
  - name: 💬 Comunidad Deepal España (Telegram)
    url: https://t.me/deepalespana_general
    about: Para dudas generales de uso, no relacionadas con un fallo o petición concreta del código.
